# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3285063b7cd52c8a145aa3adb3ea2ad14276aebbd7403c7c927bb97d9efc14f4eef1b025c362ab7560b40e059038f93e13828e177a692b5c32e37e6733caaf6a

test:
  secret_key_base: 41a22d67e3b9f9be2bf7c7722976dd8f2b831e381f47b9cdfaa14ac8d690f33aceb37eee83c99e4c6a0911290dfa44d228c9c597c669534e31dded63977e8b10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
